title: Supabase client for PHP
description: Supabase client for PHP Documentation site
baseurl: "/docs"   # â† your subpath
url: "https://codebysushil.github.io"
theme: minimal
plugins:
  - jekyll-feed

nav:
  - title: Home
    url: /
  - title: Auth
    url: /auth
